### PR TITLE
Updating Benchmark

### PR DESCRIPTION
**Pull request by aminya**
Ready to be merged

### CODE REVIEW

**Comment by Crown421** [comment]
Can you squash everything into a single commit? 21 is about a third of the total number of commits to this repo.  
I am currently working on this as well to add more depth, but that will take a bit more time, plus several hours to run it.

**Comment by aminya** [comment]
That is my style of programming, but you can squash when you merge.
Also, I will decrease the size of the array that is passed to these functions. Around `10000` is much more relevant to real-world situations, and also will cut the benchmark time

**Comment by aminya** [comment]
@Crown421 Can you select the "squash and merge" yourself? It is easier through Github

**Comment by aminya** [comment]
@Crown421 Can you select the "squash and merge" yourself? It is easier through Github. 

Please merge this, and we can fix and add other features over the master repository.
It is not straight forward to maintain a PR to a PR.

**Comment by Crown421** [comment]
Sorry, I just got to have a look. Indeed, I forgot about squash and merge. 
Could you remove the .jld2 file and add a `.gitignore` in the benchmark folder for `*.jld2`?
I don't think its necessary for everyone cloning the package to download a 20mb file.

**Comment by aminya** [comment]
@Crown421 Done! I removed jld2 file

**Pull request merged**
